### ISSUE TITLE
copr backend traceback

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2390]
```
[2022-11-28 19:40:15,409][ ERROR][PID:350650][/usr/bin/copr-backend-process-build.managed.pid-350650][background_worker_build.py:handle_task:792] Unexpected exception
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 786, in handle_task
    self.handle_build()
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 778, in handle_build
    self._get_build_job()
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 344, in _get_build_job
    self.job = BuildJob(resp.json(), self.opts)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/copr_backend/job.py", line 75, in __init__
    for key, val in task_data.items():
                    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by praiskup** [comment]
https://copr.fedorainfracloud.org/coprs/anarcoco/youtube-local/build/5072090/
Reproducible by:
```
$ copr-backend-process-build --build-id 5072090 --chroot srpm-builds
initializing bus
Sending GET request to frontend URL - https://copr.fedorainfracloud.org/backend/get-srpm-build-task/5072090/
Starting new HTTPS connection (1): copr.fedorainfracloud.org:443
https://copr.fedorainfracloud.org:443 "GET /backend/get-srpm-build-task/5072090/ HTTP/1.1" 200 5
Unexpected exception
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 786, in handle_task
    self.handle_build()
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 778, in handle_build
    self._get_build_job()
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 344, in _get_build_job
    self.job = BuildJob(resp.json(), self.opts)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/copr_backend/job.py", line 75, in __init__
    for key, val in task_data.items():
                    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
No job object from Frontend

```

**Comment by praiskup** [comment]
Seems like a #2398 duplicate.
