### ISSUE TITLE
We should re-try git clone when copr-dist-git is temporarily down

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2394]
https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-37-x86_64/05072406-R-CRAN-sparsegl/builder-live.log.gz
```
Running: git clone https://copr-dist-git.fedorainfracloud.org/git/iucar/cran/R-CRAN-sparsegl /var/lib/copr-rpmbuild/workspace/workdir-_250bprx/R-CRAN-sparsegl --depth 500 --no-single-branch --recursive

cmd: ['git', 'clone', 'https://copr-dist-git.fedorainfracloud.org/git/iucar/cran/R-CRAN-sparsegl', '/var/lib/copr-rpmbuild/workspace/workdir-_250bprx/R-CRAN-sparsegl', '--depth', '500', '--no-single-branch', '--recursive']
cwd: .
rc: 128
stdout: 
stderr: Cloning into '/var/lib/copr-rpmbuild/workspace/workdir-_250bprx/R-CRAN-sparsegl'...
fatal: unable to access 'https://copr-dist-git.fedorainfracloud.org/git/iucar/cran/R-CRAN-sparsegl/': Failed to connect to copr-dist-git.fedorainfracloud.org port 443 after 1 ms: Connection refused

Cloning into '/var/lib/copr-rpmbuild/workspace/workdir-_250bprx/R-CRAN-sparsegl'...
fatal: unable to access 'https://copr-dist-git.fedorainfracloud.org/git/iucar/cran/R-CRAN-sparsegl/': Failed to connect to copr-dist-git.fedorainfracloud.org port 443 after 1 ms: Connection refused
Running: git clone https://copr-dist-git.fedorainfracloud.org/git/iucar/cran/R-CRAN-sparsegl /var/lib/copr-rpmbuild/workspace/workdir-_250bprx/R-CRAN-sparsegl

cmd: ['git', 'clone', 'https://copr-dist-git.fedorainfracloud.org/git/iucar/cran/R-CRAN-sparsegl', '/var/lib/copr-rpmbuild/workspace/workdir-_250bprx/R-CRAN-sparsegl']
cwd: .
rc: 128
stdout: 
stderr: Cloning into '/var/lib/copr-rpmbuild/workspace/workdir-_250bprx/R-CRAN-sparsegl'...
fatal: unable to access 'https://copr-dist-git.fedorainfracloud.org/git/iucar/cran/R-CRAN-sparsegl/': Failed to connect to copr-dist-git.fedorainfracloud.org port 443 after 2 ms: Connection refused


Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/copr_rpmbuild/helpers.py", line 286, in git_clone_and_checkout
    run_cmd(clone_cmd)
  File "/usr/lib/python3.11/site-packages/copr_rpmbuild/helpers.py", line 74, in run_cmd
    raise RuntimeError(result.stderr)
RuntimeError: Cloning into '/var/lib/copr-rpmbuild/workspace/workdir-_250bprx/R-CRAN-sparsegl'...
fatal: unable to access 'https://copr-dist-git.fedorainfracloud.org/git/iucar/cran/R-CRAN-sparsegl/': Failed to connect to copr-dist-git.fedorainfracloud.org port 443 after 1 ms: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/copr-rpmbuild", line 259, in build_rpm
    distgit.produce_sources()
  File "/usr/lib/python3.11/site-packages/copr_rpmbuild/providers/distgit.py", line 34, in produce_sources
    helpers.git_clone_and_checkout(self.clone_url, self.committish,
  File "/usr/lib/python3.11/site-packages/copr_rpmbuild/helpers.py", line 291, in git_clone_and_checkout
    run_cmd(['git', 'clone', url, repo_path])
  File "/usr/lib/python3.11/site-packages/copr_rpmbuild/helpers.py", line 74, in run_cmd
    raise RuntimeError(result.stderr)
RuntimeError: Cloning into '/var/lib/copr-rpmbuild/workspace/workdir-_250bprx/R-CRAN-sparsegl'...
fatal: unable to access 'https://copr-dist-git.fedorainfracloud.org/git/iucar/cran/R-CRAN-sparsegl/': Failed to connect to copr-dist-git.fedorainfracloud.org port 443 after 2 ms: Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/copr-rpmbuild", line 134, in main
    action(args, config)
  File "/usr/bin/copr-rpmbuild", line 266, in build_rpm
    builder.archive_configs()
    ^^^^^^^
UnboundLocalError: cannot access local variable 'builder' where it is not associated with a value

```

**Comment by praiskup** [comment]
With @frostyx we decided to mark this as bug, but it is not a new one.
