### ISSUE TITLE
Error while importing SRPM

### ISSUE THREAD

**Issue by r0x0d** [fedora-copr/copr#2691]
While trying to build copr rpms with packit, I came across with an unexpected behavior during the import of a SRPM. The following below is the traceback that appears in the logs for my run.

```python
Error during source uploading, merge, or commit.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/copr_dist_git/package_import.py", line 220, in import_package
    upload_files = commands.import_srpm(srpm_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyrpkg/__init__.py", line 1931, in import_srpm
    raise rpkgError('There are uncommitted changes in your repo')
pyrpkg.errors.rpkgError: There are uncommitted changes in your repo
```

Here's the [error log](https://copr-dist-git.fedorainfracloud.org/per-task-logs/5851949.log) for further clarification. 

That happened while trying to build rpms for RHEL7, but I guess that the same could happen for RHLE8.

**Comment by praiskup** [comment]
Has the resubmit helped?  This feels like some race condition.  But we do have the locking mechanism implemented.

**Comment by praiskup** [comment]
The guilty [code](https://github.com/fedora-copr/copr/blob/a0bee3f1fae88c638c9d27082572d3d7e14fce82/dist-git/copr_dist_git/package_import.py#L218-L233).

Some questions:
- has `commands.upload()` failed?  we should have a log entry there to see what is happening
- should we re-try?
- should we stop the cycle if one of the branches fails to import?

**Comment by r0x0d** [comment]
> Has the resubmit helped? This feels like some race condition. But we do have the locking mechanism implemented.

Yes, but only after 1h-2h after we got this error. I remember that I tried to retry immediately when I saw the error, and it got stuck gain. 

Maybe something to consider is: 

- It got stuck the first time at that same point, noticed after 1h~
- Retried the build again, it got stuck for the second time, let the pipeline run for 30m-1h~
- Retried a third time and this time it worked just fine, and so far, it seems to be working as expected (haven't seen this problem again)

**Comment by praiskup** [comment]
This is inconvenient, but we did not get to solving this issue, and rpkg-util is planned to be obsoleted: #2820.
