### ISSUE TITLE
Fedora Copr - something wrong with ppc64le

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2727]
We have some performance issues with ppc64le architecture, per report from @lbarcziova and @thozza, and I can observe it even in my projects (example build: https://copr.fedorainfracloud.org/coprs/praiskup/tar-upstream-head/build/5928950/)

**Comment by FrostyX** [comment]
This traceback happens when allocating the ppc64le builders

```
Traceback (most recent call last):
  File "/var/lib/resallocserver/provision/libvirt-new", line 461, in <module>
    _main()
  File "/var/lib/resallocserver/provision/libvirt-new", line 452, in _main
    spawner.spawn()
  File "/var/lib/resallocserver/provision/libvirt-new", line 342, in spawn
    self.create_volume_from_iso(config_vol_name, '1M', config_iso,
  File "/var/lib/resallocserver/provision/libvirt-new", line 226, in create_volume_from_iso
    self.alloc_disk(name, prealloc_size, pool)
  File "/var/lib/resallocserver/provision/libvirt-new", line 152, in alloc_disk
    raise Exception("can't create '{0}' disk".format(name))
Exception: can't create 'copr_p09_01_prod_02431937_20230517_212117_config' disk
```

**Comment by praiskup** [comment]
Closing for now
