### ISSUE TITLE
copr-frontend FTBFS Rawhide

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2776]
```
+ ./manage.py test -vv
WARNING:root:no boto3 module found
Traceback (most recent call last):
  File "/builddir/build/BUILD/copr-frontend-git-29.92a6ca9/coprs_frontend/./manage.py", line 13, in <module>
    from commands.flask3_wrapper import get_flask_wrapper_command
  File "/builddir/build/BUILD/copr-frontend-git-29.92a6ca9/coprs_frontend/commands/__init__.py", line 3, in <module>
    from coprs import models
  File "/builddir/build/BUILD/copr-frontend-git-29.92a6ca9/coprs_frontend/coprs/__init__.py", line 87, in <module>
    import coprs.whoosheers
  File "/builddir/build/BUILD/copr-frontend-git-29.92a6ca9/coprs_frontend/coprs/whoosheers.py", line 9, in <module>
    from coprs import models
  File "/builddir/build/BUILD/copr-frontend-git-29.92a6ca9/coprs_frontend/coprs/models.py", line 19, in <module>
    import modulemd_tools.yaml
ModuleNotFoundError: No module named 'modulemd_tools.yaml'
```

**Comment by FrostyX** [comment]
This is  a bug caused by https://github.com/rpm-software-management/modulemd-tools/pull/53
I'll fix this on the modulemd-tools side. But please keep this one open for tracking.

**Comment by FrostyX** [comment]
The CI is fixed since https://koji.fedoraproject.org/koji/buildinfo?buildID=2218308
