### ISSUE TITLE
`task_data` passed to `BuildJob` is really often `None` type

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/copr#2816]
worker.log on backend has a ton of these:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 793, in handle_task
    self.handle_build()
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 785, in handle_build
    self._get_build_job()
  File "/usr/lib/python3.11/site-packages/copr_backend/background_worker_build.py", line 350, in _get_build_job
    self.job = BuildJob(resp.json(), self.opts)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/copr_backend/job.py", line 77, in __init__
    for key, val in task_data.items():
                    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'

```

**Comment by nikromen** [comment]
note for me so I don't forget

these exceptions happen roughly at the same time on frontend
```
2023-08-08 12:42:29,487 [ERROR][/usr/share/copr/coprs_frontend/coprs/views/backend_ns/backend_general.py:187|backend_general:get_build_record][backend: 2600:1f18:8ee:ae00:d553:8ed5:d8b6:9f83] 'NoneType' object has no attribute 'module_setup_commands'
Traceback (most recent call last):
  File "/usr/share/copr/coprs_frontend/coprs/views/backend_ns/backend_general.py", line 169, in get_build_record
    modules = copr_chroot.module_setup_commands
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ```
 
this exceptions happen in `get_build_record` which provides info about `/get-build-task/` endpoint, but `get_build_record` throws an exception, logs it and then returns None -> `/get-build-task/` returns None -> `resp.json()` in `self.job = BuildJob(resp.json(), self.opts)` returns "null"

**Comment by FrostyX** [comment]
I am sorry, I forgot about this issue and canceled the broken build, see #2904. So I accidentally got rid of your reproducer. But AFAIK we know how to reproduce it locally, so hopefully it should be fine.

**Comment by praiskup** [comment]
praiskup to help jkyjovsk with reproducing
