### ISSUE TITLE
copr-dist-git seems to fail to import because of python3-rpkg?

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2847]
```Exception raised during push: Failed to execute command.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/copr_dist_git/package_import.py", line 252, in import_package
    commands.push()
  File "/usr/lib/python3.11/site-packages/pyrpkg/__init__.py", line 2254, in push
    self._run_command(cmd, cwd=self.path)
  File "/usr/lib/python3.11/site-packages/pyrpkg/__init__.py", line 1311, in _run_command
    raise rpkgError('Failed to execute command.')
pyrpkg.errors.rpkgError: Failed to execute command.
```

**Comment by pkking** [comment]
Maybe related to  https://pagure.io/rpkg/issue/665 ?

**Comment by praiskup** [comment]
> Maybe related to https://pagure.io/rpkg/issue/665 ?

Indeed!  Thank you for the reference.  We mentioned the issue in the commit message.
