### ISSUE TITLE
`/resalloc/pools` returns 500

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/copr#2882]
see https://download.copr.fedorainfracloud.org/resalloc/pools

**Comment by FrostyX** [comment]
The traceback is:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/resallocwebui/app.py", line 47, in pools
    sys.stderr.write(pools_config)
TypeError: write() argument must be str, not tuple
```

Fixing it in https://github.com/praiskup/resalloc/pull/126

**Comment by praiskup** [comment]
I'm reopening, we still want to release a new version and deploy to production.
