### ISSUE TITLE
ImportError: cannot import name 'GroupWorkerLimit' from 'copr_common.worker_manager'

### ISSUE THREAD

**Issue by BH1SCW** [fedora-copr/copr#2951]
```
docker logs -f copr_backend-build_1
Traceback (most recent call last):
  File "/usr/bin/copr-run-dispatcher", line 11, in <module>
    from copr_backend.daemons.build_dispatcher import BuildDispatcher
  File "/usr/lib/python3.11/site-packages/copr_backend/daemons/build_dispatcher.py", line 5, in <module>
    from copr_common.worker_manager import GroupWorkerLimit
ImportError: cannot import name 'GroupWorkerLimit' from 'copr_common.worker_manager' (/usr/lib/python3.11/site-packages/copr_common/worker_manager.py)
```

```
docker logs -f copr_backend-action_1
Traceback (most recent call last):
  File "/usr/bin/copr-run-dispatcher", line 11, in <module>
    from copr_backend.daemons.build_dispatcher import BuildDispatcher
  File "/usr/lib/python3.11/site-packages/copr_backend/daemons/build_dispatcher.py", line 5, in <module>
    from copr_common.worker_manager import GroupWorkerLimit
ImportError: cannot import name 'GroupWorkerLimit' from 'copr_common.worker_manager' (/usr/lib/python3.11/site-packages/copr_common/worker_manager.py)
```

**Comment by BH1SCW** [comment]
after reading the source code I find the reason:


there was no GroupWorkerLimit from this  file
```
/usr/lib/python3.11/site-packages/copr_common/dispatcher.py
```

**Comment by praiskup** [comment]
Thank you for the ticket. You seem to be using a pre-release version of copr-backend package;  this requires a pre-release version of python3-copr-common, too.  Can you retry?

**Comment by BH1SCW** [comment]
> Thank you for the ticket. You seem to be using a pre-release version of copr-backend package; this requires a pre-release version of python3-copr-common, too. Can you retry?

Thanks for reply,  I just clone code and run 
```
docker-compose up -d
```

everything is build from current source code,  
I am not sure how can I switch pre-release version or  stable version, if you don't mind tell me more that will be cool and I can retry later.

Thanks

**Comment by FrostyX** [comment]
@BH1SCW can you please try if this helps?

```
docker-compose build --no-cache
docker-compose up -d
```

**Comment by BH1SCW** [comment]
> docker-compose build --no-cache

Great, this tips works very well, 
Thanks

**Comment by FrostyX** [comment]
Nice, glad to hear that :-)
