### ISSUE TITLE
https://copr.fedorainfracloud.org/status/batches/ returning 500

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#2992]
There's a tons of mess in error_log :-( but this part seems to be related to
my IP:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 690, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 659, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 451, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'user'
Call stack:
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/coprs_ns/coprs_general.py", line 100, in coprs_show
    return flask.render_template("coprs/show/all.html",
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 994, in update_template_context
    context.update(func())
  File "/usr/share/copr/coprs_frontend/coprs/context_processors.py", line 71, in login_menu
    if oidc_enabled(config):
  File "/usr/share/copr/coprs_frontend/coprs/oidc.py", line 23, in oidc_enabled
    logger.error("OIDC_LOGIN or OIDC_PROVIDER_NAME is empty")
Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
Arguments: ()
ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 690, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 659, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 451, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'user'
Call stack:
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/status_ns/status_general.py", line 114, in running
    return render_status("running", tasks=tasks)
  File "/usr/share/copr/coprs_frontend/coprs/views/status_ns/status_general.py", line 142, in render_status
    return flask.render_template("status.html", number=len(tasks),
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 994, in update_template_context
    context.update(func())
  File "/usr/share/copr/coprs_frontend/coprs/context_processors.py", line 71, in login_menu
    if oidc_enabled(config):
  File "/usr/share/copr/coprs_frontend/coprs/oidc.py", line 23, in oidc_enabled
    logger.error("OIDC_LOGIN or OIDC_PROVIDER_NAME is empty")
Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
Arguments: ()
ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 690, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 659, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 451, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'user'
Call stack:
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/status_ns/status_general.py", line 34, in pending
    return render_status("pending", tasks=tasks, bg_tasks_cnt=bg_tasks_cnt)
  File "/usr/share/copr/coprs_frontend/coprs/views/status_ns/status_general.py", line 142, in render_status
    return flask.render_template("status.html", number=len(tasks),
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 994, in update_template_context
    context.update(func())
  File "/usr/share/copr/coprs_frontend/coprs/context_processors.py", line 71, in login_menu
    if oidc_enabled(config):
  File "/usr/share/copr/coprs_frontend/coprs/oidc.py", line 23, in oidc_enabled
    logger.error("OIDC_LOGIN or OIDC_PROVIDER_NAME is empty")
Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
Arguments: ()
ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 690, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 659, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 451, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'user'
Call stack:
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 245, in wrapper
    return f(copr, **kwargs)
  File "/usr/share/copr/coprs_frontend/coprs/views/coprs_ns/coprs_builds.py", line 52, in copr_build
    return render_copr_build(build_id, copr)
  File "/usr/share/copr/coprs_frontend/coprs/views/coprs_ns/coprs_builds.py", line 57, in render_copr_build
    return render_template("coprs/detail/build.html", build=build, copr=copr)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 994, in update_template_context
    context.update(func())
  File "/usr/share/copr/coprs_frontend/coprs/context_processors.py", line 71, in login_menu
    if oidc_enabled(config):
  File "/usr/share/copr/coprs_frontend/coprs/oidc.py", line 23, in oidc_enabled
    logger.error("OIDC_LOGIN or OIDC_PROVIDER_NAME is empty")
Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
Arguments: ()
ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 690, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 659, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 451, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'user'
Call stack:
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/batches_ns/coprs_batches.py", line 16, in coprs_batch_detail
    return render_template("batches/detail.html", batch=batch, deps=deps)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 994, in update_template_context
    context.update(func())
  File "/usr/share/copr/coprs_frontend/coprs/context_processors.py", line 71, in login_menu
    if oidc_enabled(config):
  File "/usr/share/copr/coprs_frontend/coprs/oidc.py", line 23, in oidc_enabled
    logger.error("OIDC_LOGIN or OIDC_PROVIDER_NAME is empty")
Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
Arguments: ()
ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 690, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 659, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 451, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'user'
Call stack:
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/batches_ns/coprs_batches.py", line 16, in coprs_batch_detail
    return render_template("batches/detail.html", batch=batch, deps=deps)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 994, in update_template_context
    context.update(func())
  File "/usr/share/copr/coprs_frontend/coprs/context_processors.py", line 71, in login_menu
    if oidc_enabled(config):
  File "/usr/share/copr/coprs_frontend/coprs/oidc.py", line 23, in oidc_enabled
    logger.error("OIDC_LOGIN or OIDC_PROVIDER_NAME is empty")
Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
Arguments: ()
ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 690, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 659, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 451, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'user'
Call stack:
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/status_ns/status_general.py", line 151, in batches
    return flask.render_template("status/batch_list.html", batch_trees=trees)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 994, in update_template_context
    context.update(func())
  File "/usr/share/copr/coprs_frontend/coprs/context_processors.py", line 71, in login_menu
    if oidc_enabled(config):
  File "/usr/share/copr/coprs_frontend/coprs/oidc.py", line 23, in oidc_enabled
    logger.error("OIDC_LOGIN or OIDC_PROVIDER_NAME is empty")
Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
Arguments: ()
ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
Truncated or oversized response headers received from daemon process '127.0.0.1': /usr/share/copr/coprs_frontend/application, referer: https://copr.fedorainfracloud.org/batches/detail/104773/
ERROR:coprs:Response error: 404 The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1785, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1767, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 690, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 659, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 451, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'user'
Call stack:
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.11/site-packages/flask_restx/api.py", line 675, in error_router
    return original_handler(e)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1666, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1606, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/usr/share/copr/coprs_frontend/coprs/__init__.py", line 213, in handle_exceptions
    return error_handler.handle_error(error)
  File "/usr/share/copr/coprs_frontend/coprs/error_handlers.py", line 43, in handle_error
    return self.render(message, code), code, headers
  File "/usr/share/copr/coprs_frontend/coprs/error_handlers.py", line 121, in render
    return flask.render_template("html-error.html",
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 994, in update_template_context
    context.update(func())
  File "/usr/share/copr/coprs_frontend/coprs/context_processors.py", line 71, in login_menu
    if oidc_enabled(config):
  File "/usr/share/copr/coprs_frontend/coprs/oidc.py", line 23, in oidc_enabled
    logger.error("OIDC_LOGIN or OIDC_PROVIDER_NAME is empty")
Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
Arguments: ()
ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
/usr/lib/python3.11/site-packages/flask_sqlalchemy/__init__.py:550: SAWarning: relationship 'Build.package' will copy column package.id to column build.package_id, which conflicts with relationship(s): 'Package.builds' (copies package.id to build.package_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="builds"' to the 'Build.package' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  mapper = orm.class_mapper(type)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
    return self._fmt % values
           ~~~~~~~~~~^~~~~~~~
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 690, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 659, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/logging/__init__.py", line 451, in format
    raise ValueError('Formatting field not found in record: %s' % e)
ValueError: Formatting field not found in record: 'user'
Call stack:
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/status_ns/status_general.py", line 151, in batches
    return flask.render_template("status/batch_list.html", batch_trees=trees)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/lib/python3.11/site-packages/flask/templating.py", line 128, in _render
    app.update_template_context(context)
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 994, in update_template_context
    context.update(func())
  File "/usr/share/copr/coprs_frontend/coprs/context_processors.py", line 71, in login_menu
    if oidc_enabled(config):
  File "/usr/share/copr/coprs_frontend/coprs/oidc.py", line 23, in oidc_enabled
    logger.error("OIDC_LOGIN or OIDC_PROVIDER_NAME is empty")
Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
Arguments: ()
ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
```

**Comment by FrostyX** [comment]
I think I fixed this in PR #2902 but it probably wasn't released yet.

**Comment by praiskup** [comment]
Do you think it could cause a random 500 error?  Because the page started working after a page refresh.

**Comment by praiskup** [comment]
Indeed, it appears to be fixed after the move to the new release.
