### ISSUE TITLE
Pagure events are not triggering new builds

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3038]
Per report on irc chat:
> pgnd> pushes to my pagure repos aren't triggering my COPR rebuilds this morning.  did usage change with yesterday's down-time/updates?  Or a known issue atm?

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/fedora_messaging/twisted/consumer.py", line 224, in _read_one
    yield d
  File "/usr/lib/python3.12/site-packages/twisted/python/threadpool.py", line 269, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/twisted/python/threadpool.py", line 285, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/pagure_events.py", line 219, in __call__
    candidates = ScmPackage.get_candidates_for_rebuild(event_info.base_clone_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/pagure_events.py", line 69, in get_candidates_for_rebuild
    rows = models.Package.query \
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask_sqlalchemy/model.py", line 31, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 47, in __call__
    sess = self.registry()
           ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/util/_collections.py", line 1006, in __call__
    key = self.scopefunc()
          ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask_sqlalchemy/session.py", line 102, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

```

**Comment by pgnd** [comment]
fyi,  builds manually triggered @ COPR *do* pull from pagure & build successfully.
it appears it's just the fedmsg push/trigger from pagure

**Comment by praiskup** [comment]
I installed the following hot-fix:

```
[root@copr-fe ~][PROD]# dnf diff copr-frontend /usr/share/copr/coprs_frontend/pagure_events.py
Last metadata expiration check: 0:00:16 ago on Thu 30 Nov 2023 02:52:23 PM UTC.
--- /usr/share/copr/coprs_frontend/pagure_events.py     2023-11-23 00:00:00.000000000 +0000
+++ /usr/share/copr/coprs_frontend/pagure_events.py     2023-11-30 14:44:18.149814389 +0000
@@ -187,8 +187,11 @@
 
 
 class build_on_fedmsg_loop():
-
     def __call__(self, message):
+        with app.app_context():
+            return self.the_call(message)
+
+    def the_call(self, message):
         pp = pprint.PrettyPrinter(width=120)
 
         log.debug('Parsing...')
```

**Comment by pgnd** [comment]
> please drop a comment in the issue if you feel it is broken

i'm not sure this _is_ broken. it's just atypically slow.

  https://copr.fedorainfracloud.org/coprs/pgfed/mariadb-pgnd/build/6708610/

for a 'simple' (new pkg for me, here) .spec, 9 minutes for a rawhide build seems off ...
