### ISSUE TITLE
ISE - AttributeError: 'Package' object has no attribute 'latest_build'

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#3057]
I have seen this in log of Fedora's Copr:

```
[Wed Dec 13 10:57:43.575576 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567] ERROR:coprs:Admin-only exception
[Wed Dec 13 10:57:43.575606 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567] Request: GET https://copr.fedorainfracloud.org/coprs/ligenix/enterprise-sandbox/package/marshalparser/status_image/last_build.png
[Wed Dec 13 10:57:43.575617 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567] User: None
[Wed Dec 13 10:57:43.575628 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567] Traceback (most recent call last):
[Wed Dec 13 10:57:43.575639 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
[Wed Dec 13 10:57:43.575649 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]     rv = self.dispatch_request() 
[Wed Dec 13 10:57:43.575659 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]          ^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:57:43.575669 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
[Wed Dec 13 10:57:43.575680 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)[Wed Dec 13 10:57:43.575691 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[Wed Dec 13 10:57:43.575720 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]   File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 245, in wrapper
[Wed Dec 13 10:57:43.575732 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]     return f(copr, **kwargs)
[Wed Dec 13 10:57:43.575743 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]            ^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:57:43.575753 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]   File "/usr/share/copr/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py", line 84, in copr_package_icon
[Wed Dec 13 10:57:43.575764 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]     return send_build_icon(package.latest_build, no_cache=True) 
[Wed Dec 13 10:57:43.575774 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567]                            ^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:57:43.575784 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567] AttributeError: 'Package' object has no attribute 'latest_build'. Did you mean: 'last_build'?
[Wed Dec 13 10:57:43.576085 2023] [wsgi:error] [pid 1885134:tid 1885139] [remote 114.119.131.232:25567] ERROR:coprs:Response error: 500 Request wasn't successful, there is probably a bug in the Copr code.

```

**Comment by FrostyX** [comment]
There is an easy reproducer:

1. Create a new package, it doesn't matter what name or source type
2. **Do not** build it
3. Open the package details
4. Find the badge URL in the Status Badge section
5. Open it in the web browser
