### ISSUE TITLE
ISE psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ownername_copr_dir_uniq"

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#3058]
I have seen this in Fedora's Copr log:

```
[Wed Dec 13 10:25:02.121061 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] ERROR:coprs:Admin-only exception
[Wed Dec 13 10:25:02.121092 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] Request: POST https://copr.fedorainfracloud.org/webhooks/custom-dir/%40mock/mock-pull-requests:pr:1270/9d6af83d-7f27-4091-8161-c1098ff5a6dc/mock/
[Wed Dec 13 10:25:02.121103 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] User: None
[Wed Dec 13 10:25:02.121112 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] Traceback (most recent call last):
[Wed Dec 13 10:25:02.121123 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
[Wed Dec 13 10:25:02.121135 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     self.dialect.do_execute(
[Wed Dec 13 10:25:02.121145 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
[Wed Dec 13 10:25:02.121171 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     cursor.execute(statement, parameters)
[Wed Dec 13 10:25:02.121180 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "ownername_copr_dir_uniq"
[Wed Dec 13 10:25:02.121188 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] DETAIL:  Key (ownername, name)=(@mock, mock-pull-requests:pr:1270) already exists.
[Wed Dec 13 10:25:02.121196 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]
[Wed Dec 13 10:25:02.121204 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]
[Wed Dec 13 10:25:02.121212 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] The above exception was the direct cause of the following exception:
[Wed Dec 13 10:25:02.121220 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]
[Wed Dec 13 10:25:02.121227 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] Traceback (most recent call last):
[Wed Dec 13 10:25:02.121235 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
[Wed Dec 13 10:25:02.121243 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     rv = self.dispatch_request()
[Wed Dec 13 10:25:02.121251 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]          ^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121259 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
[Wed Dec 13 10:25:02.121267 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Wed Dec 13 10:25:02.121274 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121283 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/share/copr/coprs_frontend/coprs/views/webhooks_ns/webhooks_general.py", line 278, in webhooks_coprdir_custom
[Wed Dec 13 10:25:02.121291 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     copr_dir = CoprDirsLogic.get_or_create(copr, dirname)
[Wed Dec 13 10:25:02.121298 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121306 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/share/copr/coprs_frontend/coprs/logic/coprs_logic.py", line 694, in get_or_create
[Wed Dec 13 10:25:02.121314 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     ActionsLogic.send_createrepo(copr, dirnames=[dirname])
[Wed Dec 13 10:25:02.121322 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/share/copr/coprs_frontend/coprs/logic/actions_logic.py", line 97, in send_createrepo
[Wed Dec 13 10:25:02.121330 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     possible_dirnames = [copr_dir.name for copr_dir in copr.dirs]
[Wed Dec 13 10:25:02.121338 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]                                                        ^^^^^^^^^
[Wed Dec 13 10:25:02.121346 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 487, in __get__
[Wed Dec 13 10:25:02.121353 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     return self.impl.get(state, dict_)
[Wed Dec 13 10:25:02.121361 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121378 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 959, in get
[Wed Dec 13 10:25:02.121387 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     value = self._fire_loader_callables(state, key, passive)
[Wed Dec 13 10:25:02.121395 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121402 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 995, in _fire_loader_callables
[Wed Dec 13 10:25:02.121410 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     return self.callable_(state, passive)
[Wed Dec 13 10:25:02.121418 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121426 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/strategies.py", line 912, in _load_for_state
[Wed Dec 13 10:25:02.121434 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     return self._emit_lazyload(
[Wed Dec 13 10:25:02.121442 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]            ^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121450 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/strategies.py", line 1046, in _emit_lazyload
[Wed Dec 13 10:25:02.121458 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     result = session.execute(
[Wed Dec 13 10:25:02.121465 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]              ^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121473 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 1665, in execute
[Wed Dec 13 10:25:02.121481 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     ) = compile_state_cls.orm_pre_session_exec(
[Wed Dec 13 10:25:02.121489 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121496 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
[Wed Dec 13 10:25:02.121504 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     session._autoflush()
[Wed Dec 13 10:25:02.121512 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 2264, in _autoflush
[Wed Dec 13 10:25:02.121520 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     util.raise_(e, with_traceback=sys.exc_info()[2])
[Wed Dec 13 10:25:02.121528 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[Wed Dec 13 10:25:02.121536 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     raise exception
[Wed Dec 13 10:25:02.121543 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 2253, in _autoflush
[Wed Dec 13 10:25:02.121551 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     self.flush()
[Wed Dec 13 10:25:02.121559 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
[Wed Dec 13 10:25:02.121567 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     self._flush(objects)
[Wed Dec 13 10:25:02.121584 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
[Wed Dec 13 10:25:02.121592 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     with util.safe_reraise():
[Wed Dec 13 10:25:02.121600 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
[Wed Dec 13 10:25:02.121607 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     compat.raise_(
[Wed Dec 13 10:25:02.121615 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[Wed Dec 13 10:25:02.121623 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     raise exception
[Wed Dec 13 10:25:02.121631 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
[Wed Dec 13 10:25:02.121639 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     flush_context.execute()
[Wed Dec 13 10:25:02.121646 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
[Wed Dec 13 10:25:02.121654 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     rec.execute(self)
[Wed Dec 13 10:25:02.121662 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
[Wed Dec 13 10:25:02.121670 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     util.preloaded.orm_persistence.save_obj(
[Wed Dec 13 10:25:02.121678 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
[Wed Dec 13 10:25:02.121686 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     _emit_insert_statements(
[Wed Dec 13 10:25:02.121693 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
[Wed Dec 13 10:25:02.121701 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     result = connection._execute_20(
[Wed Dec 13 10:25:02.121709 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]              ^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121717 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
[Wed Dec 13 10:25:02.121725 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     return meth(self, args_10style, kwargs_10style, execution_options)
[Wed Dec 13 10:25:02.121733 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121740 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
[Wed Dec 13 10:25:02.121748 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     return connection._execute_clauseelement(
[Wed Dec 13 10:25:02.121756 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121764 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
[Wed Dec 13 10:25:02.121781 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     ret = self._execute_context(
[Wed Dec 13 10:25:02.121789 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]           ^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.121797 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
[Wed Dec 13 10:25:02.121805 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     self._handle_dbapi_exception(
[Wed Dec 13 10:25:02.121812 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
[Wed Dec 13 10:25:02.121820 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     util.raise_(
[Wed Dec 13 10:25:02.121828 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[Wed Dec 13 10:25:02.121836 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     raise exception
[Wed Dec 13 10:25:02.121844 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
[Wed Dec 13 10:25:02.121851 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     self.dialect.do_execute(
[Wed Dec 13 10:25:02.121859 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
[Wed Dec 13 10:25:02.121867 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     cursor.execute(statement, parameters)
[Wed Dec 13 10:25:02.121875 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
[Wed Dec 13 10:25:02.121883 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ownername_copr_dir_uniq"
[Wed Dec 13 10:25:02.121891 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] DETAIL:  Key (ownername, name)=(@mock, mock-pull-requests:pr:1270) already exists.
[Wed Dec 13 10:25:02.121899 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]
[Wed Dec 13 10:25:02.121907 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] [SQL: INSERT INTO copr_dir (name, main, ownername, copr_id) VALUES (%(name)s, %(main)s, %(ownername)s, %(copr_id)s) RETURNING copr_dir.id]
[Wed Dec 13 10:25:02.121938 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] [parameters: {'name': 'mock-pull-requests:pr:1270', 'main': False, 'ownername': '@mock', 'copr_id': 29795}]
[Wed Dec 13 10:25:02.123809 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] (Background on this error at: https://sqlalche.me/e/14/gkpj)
[Wed Dec 13 10:25:02.124147 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] ERROR:coprs:Response error: gkpj Database error, contact admin
[Wed Dec 13 10:25:02.127167 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] INFO:coprs:Webhook (0) data: b'ewogICJ0eXBlIjogIlBSIiwKICAicHJfaWQiOiAiMTI3MCIsCiAgImdpdF9oYXNoIjogImUyN2QzMDc4N2IxMmQ5OTMxMDA4ZGQ4MzljYWIzZmY2Y2JjYmVmMzMiCn0='
[Wed Dec 13 10:25:02.127848 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] mod_wsgi (pid=1882891): Exception occurred processing WSGI script '/usr/share/copr/coprs_frontend/application'.
[Wed Dec 13 10:25:02.128398 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] Traceback (most recent call last):
[Wed Dec 13 10:25:02.128667 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 2552, in __call__
[Wed Dec 13 10:25:02.128682 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     return self.wsgi_app(environ, start_response)
[Wed Dec 13 10:25:02.128691 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.128709 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 2536, in wsgi_app
[Wed Dec 13 10:25:02.128718 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     return response(environ, start_response)
[Wed Dec 13 10:25:02.128726 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:25:02.128741 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]   File "/usr/lib/python3.12/site-packages/werkzeug/wrappers/response.py", line 630, in __call__
[Wed Dec 13 10:25:02.128750 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720]     start_response(status, headers)
[Wed Dec 13 10:25:02.128772 2023] [wsgi:error] [pid 1882891:tid 1882896] [remote 20.97.191.37:30720] ValueError: status code is not a 3 digit integer
```

**Comment by FrostyX** [comment]
Probably related to #2076

**Comment by FrostyX** [comment]
I am failing to reproduce this. I tried tweaking unit tests in `test_webhooks.py`, and tried triggering multiple webhooks in parallel, e.g.

```
parallel curl -X POST ::: $(for i in {1..20}; do echo "http://localhost:5000/webhooks/custom-dir/%40copr/webhooks-reproducer:pr:4/970c939a-d682-4b1e-9371-ab7c6e534bed/copr-cli"; done)
```

Everything worked fine. Do you have any idea what may be the cause of this?

**Comment by xsuchy** [comment]
I think this is a race condition. We create new CoprDir by
```
copr_dir = models.CoprDir(name=dirname, copr=copr, main=False)
ActionsLogic.send_createrepo(copr, dirnames=[dirname])
```
but at then end of send_createrepo when SQLalchemy flushes, someone already created that dir in the meantime.
I will try to draft a PR.
