### ISSUE TITLE
ISE -  ValueError: status code is not a 3 digit integer

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#3073]
I see this in production log:
```[Tue Dec 19 21:55:20.153057 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] ERROR:coprs:Admin-only exception
[Tue Dec 19 21:55:20.153090 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] Request: GET https://copr.fedorainfracloud.org/coprs/packit/cockpit-project-cockpit-podman-1512/repo/fedora-39/packit-cockpit-project-cockpit-podman-1512-fedora-39.repo
[Tue Dec 19 21:55:20.153102 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] User: None
[Tue Dec 19 21:55:20.153112 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] Traceback (most recent call last):
[Tue Dec 19 21:55:20.153122 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
[Tue Dec 19 21:55:20.153132 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     self.dialect.do_execute(
[Tue Dec 19 21:55:20.153142 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
[Tue Dec 19 21:55:20.153152 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     cursor.execute(statement, parameters)
[Tue Dec 19 21:55:20.153162 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "counter_stat_pkey"
[Tue Dec 19 21:55:20.153172 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] DETAIL:  Key (name)=(repo_dl_stat::packit@cockpit-project-cockpit-podman-1512:fedora-39) already exists.
[Tue Dec 19 21:55:20.153182 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] 
[Tue Dec 19 21:55:20.153191 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] 
[Tue Dec 19 21:55:20.153202 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] The above exception was the direct cause of the following exception:
[Tue Dec 19 21:55:20.153211 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] 
[Tue Dec 19 21:55:20.153237 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] Traceback (most recent call last):
[Tue Dec 19 21:55:20.153247 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
[Tue Dec 19 21:55:20.153257 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     rv = self.dispatch_request()
[Tue Dec 19 21:55:20.153267 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]          ^^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.153277 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
[Tue Dec 19 21:55:20.153287 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Tue Dec 19 21:55:20.153297 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.153307 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 258, in wrapper
[Tue Dec 19 21:55:20.153316 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     return f(copr_dir, **kwargs)
[Tue Dec 19 21:55:20.153326 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]            ^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.153336 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/share/copr/coprs_frontend/coprs/views/coprs_ns/coprs_general.py", line 860, in generate_repo_file
[Tue Dec 19 21:55:20.153346 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     return render_generate_repo_file(copr_dir, name_release, arch)
[Tue Dec 19 21:55:20.153355 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.153365 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib/python3.12/site-packages/flask_caching/__init__.py", line 872, in decorated_function
[Tue Dec 19 21:55:20.153375 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     rv = self._call_fn(f, *args, **kwargs) 
[Tue Dec 19 21:55:20.153386 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.153395 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib/python3.12/site-packages/flask_caching/__init__.py", line 175, in _call_fn
[Tue Dec 19 21:55:20.153405 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     return ensure_sync(fn)(*args, **kwargs)
[Tue Dec 19 21:55:20.153415 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.153425 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/share/copr/coprs_frontend/coprs/views/coprs_ns/coprs_general.py", line 981, in render_generate_repo_file
[Tue Dec 19 21:55:20.153434 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     db.session.commit()
[Tue Dec 19 21:55:20.153444 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "<string>", line 2, in commit
[Tue Dec 19 21:55:20.153453 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
[Tue Dec 19 21:55:20.153463 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     self._transaction.commit(_to_root=self.future)
[Tue Dec 19 21:55:20.153473 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 832, in commit
[Tue Dec 19 21:55:20.153496 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     self._prepare_impl()
[Tue Dec 19 21:55:20.153506 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
[Tue Dec 19 21:55:20.153516 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     self.session.flush()
[Tue Dec 19 21:55:20.153526 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 3449, in flush 
[Tue Dec 19 21:55:20.153536 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     self._flush(objects)
[Tue Dec 19 21:55:20.153546 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
[Tue Dec 19 21:55:20.153556 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     with util.safe_reraise():
[Tue Dec 19 21:55:20.153565 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
[Tue Dec 19 21:55:20.153575 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     compat.raise_(
[Tue Dec 19 21:55:20.153585 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[Tue Dec 19 21:55:20.153595 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     raise exception
[Tue Dec 19 21:55:20.153604 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
[Tue Dec 19 21:55:20.153614 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     flush_context.execute()
[Tue Dec 19 21:55:20.153624 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
[Tue Dec 19 21:55:20.153634 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     rec.execute(self)
[Tue Dec 19 21:55:20.153644 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
[Tue Dec 19 21:55:20.153653 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     util.preloaded.orm_persistence.save_obj(
[Tue Dec 19 21:55:20.153663 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
[Tue Dec 19 21:55:20.153673 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     _emit_insert_statements(
[Tue Dec 19 21:55:20.153683 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
[Tue Dec 19 21:55:20.153693 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     c = connection._execute_20(
[Tue Dec 19 21:55:20.153702 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]         ^^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.153712 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
[Tue Dec 19 21:55:20.153722 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     return meth(self, args_10style, kwargs_10style, execution_options)
[Tue Dec 19 21:55:20.153732 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.153742 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
[Tue Dec 19 21:55:20.153764 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     return connection._execute_clauseelement(
[Tue Dec 19 21:55:20.153774 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.153784 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
[Tue Dec 19 21:55:20.153793 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     ret = self._execute_context(
[Tue Dec 19 21:55:20.153803 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]           ^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.153813 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
[Tue Dec 19 21:55:20.153823 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     self._handle_dbapi_exception(
[Tue Dec 19 21:55:20.153833 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
[Tue Dec 19 21:55:20.153843 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     util.raise_(
[Tue Dec 19 21:55:20.153853 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
[Tue Dec 19 21:55:20.153863 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     raise exception
[Tue Dec 19 21:55:20.153872 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
[Tue Dec 19 21:55:20.153883 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     self.dialect.do_execute(
[Tue Dec 19 21:55:20.153892 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
[Tue Dec 19 21:55:20.153902 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     cursor.execute(statement, parameters)
[Tue Dec 19 21:55:20.153912 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "counter_stat_pkey"
[Tue Dec 19 21:55:20.153950 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] DETAIL:  Key (name)=(repo_dl_stat::packit@cockpit-project-cockpit-podman-1512:fedora-39) already exists.
[Tue Dec 19 21:55:20.153960 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]
[Tue Dec 19 21:55:20.153970 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] [SQL: INSERT INTO counter_stat (name, counter_type, counter) VALUES (%(name)s, %(counter_type)s, %(counter)s)]
[Tue Dec 19 21:55:20.153980 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] [parameters: {'name': 'repo_dl_stat::packit@cockpit-project-cockpit-podman-1512:fedora-39', 'counter_type': 'repo_dl', 'counter': 1}]
[Tue Dec 19 21:55:20.153990 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] (Background on this error at: https://sqlalche.me/e/14/gkpj)
[Tue Dec 19 21:55:20.154243 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] ERROR:coprs:Response error: gkpj Database error, contact admin
[Tue Dec 19 21:55:20.156748 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] mod_wsgi (pid=2590221): Exception occurred processing WSGI script '/usr/share/copr/coprs_frontend/application'.
[Tue Dec 19 21:55:20.157413 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] Traceback (most recent call last):
[Tue Dec 19 21:55:20.157692 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 2552, in __call__
[Tue Dec 19 21:55:20.157711 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     return self.wsgi_app(environ, start_response)
[Tue Dec 19 21:55:20.157721 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.157744 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 2536, in wsgi_app
[Tue Dec 19 21:55:20.157756 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     return response(environ, start_response)
[Tue Dec 19 21:55:20.157766 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Tue Dec 19 21:55:20.157786 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]   File "/usr/lib/python3.12/site-packages/werkzeug/wrappers/response.py", line 630, in __call__
[Tue Dec 19 21:55:20.157797 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050]     start_response(status, headers)
[Tue Dec 19 21:55:20.157824 2023] [wsgi:error] [pid 2590221:tid 2590236] [remote 13.59.72.67:57050] ValueError: status code is not a 3 digit integer
```

**Comment by FrostyX** [comment]
Related but probably not duplicate #3058
