### ISSUE TITLE
Branch fedora

### ISSUE THREAD

**Issue by nikromen** [fedora-copr/copr#3138]

**Comment by FrostyX** [comment]
```
Handling builds in copr '@sssd/pr7177', chroot 'fedora-rawhide-x86_64'
Traceback (most recent call last):
  File "/usr/bin/copr-frontend", line 143, in <module>
    app.cli()
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/copr-frontend", line 109, in wrapper
    sys.exit(bool(function(*args, **kwargs)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/commands/branch_fedora.py", line 27, in branch_fedora
    branch_fedora_function(fedora_version, retry_forked, branch)
  File "/usr/share/copr/coprs_frontend/commands/branch_fedora.py", line 48, in branch_fedora_function
    rawhide_to_release_function(rawhide_chroot, new_chroot, retry_forked)
  File "/usr/share/copr/coprs_frontend/commands/rawhide_to_release.py", line 82, in rawhide_to_release_function
    .filter(models.Build.copr_dir_id == copr.main_dir.id)
                                        ^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/models.py", line 457, in main_dir
    return CoprDir.query.filter(CoprDir.copr_id==self.id).filter(CoprDir.main==True).one()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/result.py", line 1522, in one
    return self._only_one_row(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/result.py", line 562, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required
```

I will need to hotfix this in production

**Comment by FrostyX** [comment]
> I will need to hotfix this in production

It was probably some race with the project currently being deleted. I re-run the command again and it finished properly. Also, the chroots are now enabled.

https://lists.fedoraproject.org/archives/list/copr-devel@lists.fedorahosted.org/thread/TPIVZRXNBGTIUXGTV46PA6GMVNLXJUIW/
