### ISSUE TITLE
vmhost-x86-copr02.rdu-cc.fedoraproject.org doesn't start machines

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3233]
```
wait 1.0s, remains 1.0s
timeout!
stopping per kill event
DEBUG:root: -> exit_status=1, time=180.173s
DEBUG:root:Cleaning up ...
DEBUG:root:cleanup 50_shut_down_vm_destroy
DEBUG:root:cmd: virsh -c qemu+ssh://copr@vmhost-x86-copr02.rdu-cc.fedoraproject.org/system destroy copr_hv_x86_64_02_dev_01706141_20240423_081620
Domain 'copr_hv_x86_64_02_dev_01706141_20240423_081620' destroyed

DEBUG:root: -> exit_status=0, time=1.062s
DEBUG:root:cleanup 51_shut_down_vm_undefine
DEBUG:root:cmd: virsh -c qemu+ssh://copr@vmhost-x86-copr02.rdu-cc.fedoraproject.org/system undefine copr_hv_x86_64_02_dev_01706141_20240423_081620 --nvram
Domain 'copr_hv_x86_64_02_dev_01706141_20240423_081620' has been undefined

DEBUG:root: -> exit_status=0, time=0.217s
DEBUG:root:cleanup 80_delete_disk_copr_hv_x86_64_02_dev_01706141_20240423_081620_config
DEBUG:root:cmd: virsh -c qemu+ssh://copr@vmhost-x86-copr02.rdu-cc.fedoraproject.org/system vol-delete copr_hv_x86_64_02_dev_01706141_20240423_081620_config --pool images
Vol copr_hv_x86_64_02_dev_01706141_20240423_081620_config deleted

DEBUG:root: -> exit_status=0, time=0.228s
DEBUG:root:cleanup 80_delete_disk_copr_hv_x86_64_02_dev_01706141_20240423_081620_root
DEBUG:root:cmd: virsh -c qemu+ssh://copr@vmhost-x86-copr02.rdu-cc.fedoraproject.org/system vol-delete copr_hv_x86_64_02_dev_01706141_20240423_081620_root --pool images
Vol copr_hv_x86_64_02_dev_01706141_20240423_081620_root deleted

DEBUG:root: -> exit_status=0, time=0.768s
DEBUG:root:cleanup 80_delete_disk_copr_hv_x86_64_02_dev_01706141_20240423_081620_swap
DEBUG:root:cmd: virsh -c qemu+ssh://copr@vmhost-x86-copr02.rdu-cc.fedoraproject.org/system vol-delete copr_hv_x86_64_02_dev_01706141_20240423_081620_swap --pool images
Vol copr_hv_x86_64_02_dev_01706141_20240423_081620_swap deleted

DEBUG:root: -> exit_status=0, time=0.244s
Traceback (most recent call last):
  File "/var/lib/resallocserver/provision/libvirt-new", line 461, in <module>
    _main()
  File "/var/lib/resallocserver/provision/libvirt-new", line 452, in _main
    spawner.spawn()
  File "/var/lib/resallocserver/provision/libvirt-new", line 372, in spawn
    self.wait_for_ssh(self.ipv6)
  File "/var/lib/resallocserver/provision/libvirt-new", line 90, in wait_for_ssh
    raise Exception("waiting not successful")
Exception: waiting not successful
```

**Comment by nikromen** [comment]
https://pagure.io/fedora-infra/ansible/pull-request/1976 + executing playbook against hv02 fixed this
