### ISSUE TITLE
Error 500: Unknown error copr.fp.o/coprs/g/python/python3.13/package/anaconda/rebuild

### ISSUE THREAD

**Issue by hroncok** [fedora-copr/copr#3284]
1. Go to https://copr.fedorainfracloud.org/coprs/g/python/python3.13/package/anaconda
 2. Click Rebuild
 3. Leads to https://copr.fedorainfracloud.org/coprs/g/python/python3.13/package/anaconda/rebuild

![image](https://github.com/fedora-copr/copr/assets/2401856/71a922eb-53cb-45bd-9e3e-54fc2c8e5264)

 Error 500: Unknown error
Request wasn't successful, there is probably a bug in the Copr code.

**Comment by FrostyX** [comment]
Thank you @hroncok, this was surely caused by the yesterday's release. I am taking a look.

**Comment by FrostyX** [comment]
Attaching the traceback for the posterity:

```
Request: GET http://127.0.0.1:5000/coprs/g/copr/copr/package/copr-cli/rebuild
User: frostyx
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/copr/frontend/coprs_frontend/coprs/views/misc.py", line 207, in wrapper
    return f(copr, **kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/opt/copr/frontend/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py", line 163, in copr_rebuild_package
    form = form(copr.active_chroots, package)(data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/copr/frontend/coprs_frontend/coprs/forms.py", line 1400, in __new__
    return _get_build_form(active_chroots, PackageFormScm, package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/copr/frontend/coprs_frontend/coprs/forms.py", line 1276, in _get_build_form
    package_timeout, seconds_to_pretty_hours(package_timeout)),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/copr/frontend/coprs_frontend/coprs/forms.py", line 795, in seconds_to_pretty_hours
    minutes = round(sec / 60)
                    ~~~~^~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by FrostyX** [comment]
PR #3285 fixes the issue and I hotfixed it in production.

**Comment by hroncok** [comment]
The page loads now. Thanks.
