### ISSUE TITLE
Error 500 instead of 404?

### ISSUE THREAD

**Issue by praiskup** [fedora-copr/copr#3457]
```
ERROR:coprs:Admin-only exception
Request: GET https://copr.fedorainfracloud.org/backend/get-build-task/6742605-fedora-39-aarch64:
User: None
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/views/backend_ns/backend_general.py", line 368, in get_build_task
    task = BuildsLogic.get_build_task(task_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 463, in get_build_task
    build_chroot = BuildChrootsLogic.get_by_build_id_and_name(build_id, chroot_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 1501, in get_by_build_id_and_name
    mc = MockChrootsLogic.get_from_name(name).one()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/result.py", line 1522, in one
    return self._only_one_row(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/result.py", line 562, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required
ERROR:coprs:Response error: 500 Database error, contact admin
```

**Comment by nikromen** [comment]
This is really old log from the end of 2023 - https://copr.fedorainfracloud.org/coprs/petersen/haskell-language-server/build/6742605/

I tried to replicate this, but I am getting correct responses on this one

```
$ curl -w "Code: %{http_code}\n" -X GET https://copr.fedorainfracloud.org/backend/get-build-task/6742605-fedora-39-aarch64
null
Code: 200
```

Also, I recall we had problems with the frontend <-> backend protocol and we were fixing it in PRs like #2405 or #2842 so this seems like it's more or less covered.

yet still I wonder - if the task exists, why the error in the logs? Perhaps racy incident because of branching? That'd make sense since if you want to fetch nonexisting - future - fedora, you get exactly the same error:

```
$ curl -w "Code: %{http_code}\n" -X GET https://copr.fedorainfracloud.org/backend/get-build-task/8711675-fedora-43-x86_64
<some html code>
Code: 500
```

and logs:

```
Request: GET https://copr.fedorainfracloud.org/backend/get-build-task/8711675-fedora-43-x86_64
User: None
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.13/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/views/backend_ns/backend_general.py", line 368, in get_build_task
    task = BuildsLogic.get_build_task(task_id)
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 463, in get_build_task
    build_chroot = BuildChrootsLogic.get_by_build_id_and_name(build_id, chroot_name)
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 1501, in get_by_build_id_and_name
    mc = MockChrootsLogic.get_from_name(name).one()
  File "/usr/lib64/python3.13/site-packages/sqlalchemy/orm/query.py", line 2778, in one
    return self._iter().one()  # type: ignore
           ~~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/site-packages/sqlalchemy/engine/result.py", line 1810, in one
    return self._only_one_row(
           ~~~~~~~~~~~~~~~~~~^
        raise_for_second_row=True, raise_for_none=True, scalar=False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib64/python3.13/site-packages/sqlalchemy/engine/result.py", line 752, in _only_one_row
    raise exc.NoResultFound(
        "No row was found when one was required"
    )
sqlalchemy.exc.NoResultFound: No row was found when one was required
```

**Comment by praiskup** [comment]
> I tried to replicate this, but I am getting correct responses on this one

Is it because fedora 39 chroot appeared (got enabled) in the project in the meantime?

**Comment by nikromen** [comment]
sadly no... t looking to copr's branching history - F39 was branched on 11-08-2023 but the build dates to 12-12-2023
